version: '3.7'
services:
  flask-api:
    build:
      context: ./flask-api
    command: flask run --host=0.0.0.0
    ports:
      - "5000:5000"

  st-app:
    build:
      context: ./st-app
    ports:
      - "8501:8501" 
    depends_on:
      - flask-api
