FROM python:3.11-slim-bookworm

WORKDIR /app

COPY requirements.txt .
COPY api.py .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

ENV FLASK_APP=api.py

CMD ["flask", "run", "--host=0.0.0.0"]